"""
kde_dashboard.py
================
KDE Sports Platform — HTML Report Generator & Terminal Dashboard

Generates self-contained HTML reports and a text-based terminal dashboard.
No external dependencies — pure Python stdlib.
"""

from __future__ import annotations

import os
from datetime import date, timedelta
from pathlib import Path

# ---------------------------------------------------------------------------
# HTMLReportGenerator
# ---------------------------------------------------------------------------

_CSS = """
body{font-family:sans-serif;background:#0d1117;color:#e6edf3;padding:2rem;max-width:1000px;margin:auto;}
h1{color:#58a6ff;} h2{color:#79c0ff;border-bottom:1px solid #30363d;padding-bottom:.5rem;}
h3{color:#56d364;}
table{border-collapse:collapse;width:100%;margin:1rem 0;}
th,td{border:1px solid #30363d;padding:.5rem 1rem;text-align:left;}
th{background:#161b22;}
pre{background:#161b22;padding:1rem;border-radius:6px;overflow-x:auto;font-size:.9rem;}
.badge{display:inline-block;padding:.2rem .6rem;border-radius:4px;font-size:.85rem;font-weight:bold;}
.green{background:#1f6b2e;color:#56d364;}
.yellow{background:#5a4a00;color:#e3b341;}
.red{background:#6e1f1f;color:#f85149;}
.card{background:#161b22;border:1px solid #30363d;border-radius:6px;padding:1rem;margin:.5rem 0;}
.prob-bar-wrap{background:#21262d;border-radius:4px;height:18px;width:200px;display:inline-block;vertical-align:middle;}
.prob-bar{height:18px;background:#58a6ff;border-radius:4px;display:block;}
footer{margin-top:2rem;color:#484f58;font-size:.8rem;border-top:1px solid #30363d;padding-top:1rem;}
"""

_HTML_WRAP = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>{css}</style>
</head>
<body>
{body}
<footer>Generated by KDE Sports Agent &bull; {date} &bull; Local processing only</footer>
</body>
</html>"""


def _wrap(title: str, body: str) -> str:
    return _HTML_WRAP.format(
        title = title,
        css   = _CSS,
        body  = body,
        date  = date.today().isoformat(),
    )


def _badge(text: str, level: str = "green") -> str:
    cls = {"low": "green", "moderate": "yellow",
           "high": "red", "critical": "red"}.get(level, "green")
    return f'<span class="badge {cls}">{text}</span>'


def _prob_bar(value: float, max_width: int = 200) -> str:
    w = max(2, int(value * max_width))
    return (
        f'<div class="prob-bar-wrap">'
        f'<div class="prob-bar" style="width:{w}px"></div>'
        f'</div> {value:.1%}'
    )


def _text_bar(value: float, label: str = "", max_width: int = 25) -> str:
    bar = "█" * int(value * max_width)
    return f"{label:<20} |{bar:<{max_width}}| {value:.0%}"


class HTMLReportGenerator:
    """
    Generates self-contained HTML files (CSS inline, no external deps).
    """

    def __init__(
        self,
        assistant=None,
        platform=None,
    ) -> None:
        self._assistant = assistant
        self._platform  = platform

    # ── Pre-Match Brief ───────────────────────────────────────────────────

    def pre_match_brief(
        self,
        home_team:    str,
        away_team:    str,
        squad:        list[dict] = None,
        home_factors: dict       = None,
        away_factors: dict       = None,
        sport:        str        = "football",
    ) -> str:
        squad        = squad        or []
        home_factors = home_factors or {}
        away_factors = away_factors or {}

        if self._platform is None:
            from prediction_engine import PredictionPlatform
            platform = PredictionPlatform()
        else:
            platform = self._platform

        brief = platform.pre_match_brief(
            home_team, away_team, sport, squad, home_factors, away_factors
        )
        mp = brief["match_prediction"]
        tp = brief["tactical_analysis"]

        risk_rows = ""
        for rp in brief["squad_risk"]:
            risk_rows += (
                f"<tr><td>{rp.athlete_name}</td>"
                f"<td>{_badge(rp.risk_level, rp.risk_level)}</td>"
                f"<td>{', '.join(rp.recommendations[:1])}</td></tr>\n"
            )

        body = f"""
<h1>⚽ Pre-Match Brief</h1>
<div class="card">
  <h2>{home_team} vs {away_team}</h2>
  <p>Sport: <strong>{sport}</strong></p>
</div>

<h2>📊 Match Outlook</h2>
<table>
<tr><th>Outcome</th><th>Probability</th><th>Visualisation</th></tr>
<tr><td>{home_team} Win</td><td>{mp.p_home_win:.1%}</td><td>{_prob_bar(mp.p_home_win)}</td></tr>
<tr><td>Draw</td><td>{mp.p_draw:.1%}</td><td>{_prob_bar(mp.p_draw)}</td></tr>
<tr><td>{away_team} Win</td><td>{mp.p_away_win:.1%}</td><td>{_prob_bar(mp.p_away_win)}</td></tr>
</table>
<p><strong>Prediction:</strong> {mp.prediction} &nbsp;|&nbsp;
   <strong>Confidence:</strong> {mp.confidence:.0%}</p>

<h2>🧠 Tactical Analysis</h2>
<div class="card">
<p>{tp.matchup_summary}</p>
<ul>
<li><strong>Home advantage:</strong> {tp.home_advantage}</li>
<li><strong>Away advantage:</strong> {tp.away_advantage}</li>
<li><strong>Home style:</strong> {tp.home_predicted_style}</li>
<li><strong>Away style:</strong> {tp.away_predicted_style}</li>
</ul>
</div>

<h2>🏥 Squad Risk</h2>
<table>
<tr><th>Player</th><th>Risk</th><th>Recommendation</th></tr>
{risk_rows if risk_rows else '<tr><td colspan="3">No squad data provided</td></tr>'}
</table>
"""
        return _wrap(f"Pre-Match Brief: {home_team} vs {away_team}", body)

    # ── Weekly Performance ────────────────────────────────────────────────

    def weekly_performance(
        self,
        profile_name: str,
        week_offset:  int  = 0,
        sessions:     list = None,
    ) -> str:
        sessions = sessions or []
        today    = date.today()
        week_start = today - timedelta(days=today.weekday() + week_offset * 7)
        week_end   = week_start + timedelta(days=6)

        session_rows = ""
        for s in sessions:
            session_rows += (
                f"<tr><td>{s.get('date','')}</td>"
                f"<td>{s.get('session_type','')}</td>"
                f"<td>{s.get('rpe','')}</td>"
                f"<td>{s.get('notes','')}</td></tr>\n"
            )

        body = f"""
<h1>📅 Weekly Performance Report</h1>
<div class="card">
  <p>Athlete: <strong>{profile_name}</strong></p>
  <p>Week: <strong>{week_start.isoformat()} → {week_end.isoformat()}</strong></p>
</div>

<h2>🏃 Sessions</h2>
<table>
<tr><th>Date</th><th>Type</th><th>RPE</th><th>Notes</th></tr>
{session_rows if session_rows else '<tr><td colspan="4">No sessions this week</td></tr>'}
</table>

<h2>📈 Summary</h2>
<div class="card">
  <p>Total sessions: <strong>{len(sessions)}</strong></p>
  {'<p>Avg RPE: <strong>' + f"{sum(s.get('rpe',0) for s in sessions)/len(sessions):.1f}" + '</strong></p>' if sessions else ''}
</div>
"""
        return _wrap(f"Weekly Performance — {profile_name}", body)

    # ── Season Dashboard ──────────────────────────────────────────────────

    def season_dashboard(
        self,
        profile_name: str,
        history:      list = None,
    ) -> str:
        history = history or []
        body = f"""
<h1>🏆 Season Dashboard</h1>
<div class="card">
  <p>Athlete: <strong>{profile_name}</strong></p>
  <p>Season entries: <strong>{len(history)}</strong></p>
</div>

<h2>📋 Plan History</h2>
<table>
<tr><th>Date</th><th>Focus</th><th>Fulcrum</th></tr>
{"".join(f"<tr><td>{h.get('date','')}</td><td>{h.get('primary_focus','')}</td><td>{h.get('fulcrum','')}</td></tr>" for h in history[:30])}
</table>
"""
        return _wrap(f"Season Dashboard — {profile_name}", body)

    # ── Squad Risk Overview ───────────────────────────────────────────────

    def squad_risk_overview(self, squad: list[dict]) -> str:
        """
        squad: list of dicts with name, recovery_score, load_7d, muscle_soreness.
        """
        if self._platform is None:
            from prediction_engine import PredictionPlatform
            platform = PredictionPlatform()
        else:
            platform = self._platform

        rows = ""
        for player in squad:
            name = player.get("name", "Unknown")
            rp   = platform.injury.predict(
                name,
                recovery_score  = player.get("recovery_score",  0.7),
                load_7d         = player.get("load_7d",         0.5),
                muscle_soreness = player.get("muscle_soreness", 0.3),
            )
            rows += (
                f"<tr><td>{name}</td>"
                f"<td>{_badge(rp.risk_level, rp.risk_level)}</td>"
                f"<td>{rp.days_to_risk} days</td>"
                f"<td>{', '.join(rp.recommendations[:1])}</td></tr>\n"
            )

        body = f"""
<h1>🏥 Squad Risk Overview</h1>
<table>
<tr><th>Player</th><th>Risk Level</th><th>Time to Risk</th><th>Recommendation</th></tr>
{rows if rows else '<tr><td colspan="4">No players provided</td></tr>'}
</table>
"""
        return _wrap("Squad Risk Overview", body)

    # ── Save ─────────────────────────────────────────────────────────────

    def save(self, html: str, path: str) -> str:
        """Write HTML to path and return path."""
        p = Path(path).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(html, encoding="utf-8")
        return str(p)


# ---------------------------------------------------------------------------
# TerminalDashboard
# ---------------------------------------------------------------------------

# ANSI colour codes
_GREEN  = "\033[92m"
_YELLOW = "\033[93m"
_RED    = "\033[91m"
_CYAN   = "\033[96m"
_BOLD   = "\033[1m"
_RESET  = "\033[0m"

_RISK_COLOURS = {
    "low":      _GREEN,
    "moderate": _YELLOW,
    "high":     _RED,
    "critical": _RED + _BOLD,
}


class TerminalDashboard:
    """
    Text-based dashboard for terminal display.
    Uses only print() — no curses, no rich, no blessed.
    """

    def __init__(self, use_colour: bool = True) -> None:
        self._colour = use_colour and _terminal_supports_colour()

    def _c(self, text: str, code: str) -> str:
        if self._colour:
            return f"{code}{text}{_RESET}"
        return text

    # ── Morning Brief ─────────────────────────────────────────────────────

    def morning_brief(self, plan, wearable: str = "") -> None:
        """Print formatted morning briefing to stdout."""
        print()
        print(self._c("═" * 50, _CYAN))
        print(self._c("  🌅  MORNING BRIEFING", _BOLD + _CYAN))
        print(self._c("═" * 50, _CYAN))
        if wearable:
            print(f"  Wearable  : {wearable}")
        if hasattr(plan, "primary_focus"):
            print(f"  Focus     : {self._c(plan.primary_focus, _BOLD)}")
            print(f"  Activation: {plan.activation:.0%}")
            print(f"  Fulcrum   : {plan.fulcrum:.3f}")
            if plan.tasks:
                print(f"\n  {self._c('Tasks:', _CYAN)}")
                for t in plan.tasks[:5]:
                    print(f"    {t.time_slot}  {t.title} ({t.duration_min}min)")
            if plan.warnings:
                print(f"\n  {self._c('⚠ Warnings:', _YELLOW)}")
                for w in plan.warnings:
                    print(f"    {self._c(w, _YELLOW)}")
        print(self._c("═" * 50, _CYAN))
        print()

    # ── Match Prediction ──────────────────────────────────────────────────

    def match_prediction(self, pred) -> None:
        """Print formatted match prediction with ASCII probability bars."""
        print()
        print(self._c("═" * 50, _CYAN))
        print(self._c(f"  ⚽  {pred.subject}", _BOLD + _CYAN))
        print(self._c("═" * 50, _CYAN))
        print(f"  Prediction : {self._c(pred.prediction, _BOLD)}")
        print(f"  Confidence : {pred.confidence:.0%}")
        print()
        dist = pred.distribution
        for outcome, prob in dist.items():
            bar_len = int(prob * 30)
            bar     = "█" * bar_len + "░" * (30 - bar_len)
            label   = outcome.replace("_", " ").title()
            colour  = _GREEN if prob == max(dist.values()) else _RESET
            print(f"  {label:<15} {self._c(bar, colour)}  {prob:.1%}")
        print()
        print(f"  Margin est.: {pred.predicted_margin:+.1f}")
        print(self._c("═" * 50, _CYAN))
        print()

    # ── Squad Risk ────────────────────────────────────────────────────────

    def squad_risk(self, risks: list) -> None:
        """Print squad risk table with coloured risk levels."""
        print()
        print(self._c("═" * 60, _CYAN))
        print(self._c("  🏥  SQUAD RISK OVERVIEW", _BOLD + _CYAN))
        print(self._c("═" * 60, _CYAN))
        print(f"  {'Player':<22} {'Risk':<12} {'Days':<8} Recommendation")
        print("  " + "─" * 55)
        for rp in risks:
            colour = _RISK_COLOURS.get(rp.risk_level, _RESET)
            rec    = rp.recommendations[0] if rp.recommendations else "Monitor"
            level  = self._c(f"{rp.risk_level:<12}", colour)
            print(f"  {rp.athlete_name:<22} {level} {rp.days_to_risk:<8d} {rec}")
        print(self._c("═" * 60, _CYAN))
        print()


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _terminal_supports_colour() -> bool:
    """Return True if the terminal likely supports ANSI colours."""
    if not hasattr(os, "isatty"):
        return False
    return os.isatty(1) and os.environ.get("TERM", "") != "dumb"
