"""
prism_plan_telemetry.py
=======================
Per-step execution telemetry for DailyPlans.

Closes the gap between KDE.ask() producing a plan and OutcomeTracker
recording chain outcomes: until now those two flows never linked back to
the originating plan step, so re-plan had no signal about which tasks
actually got done overnight.

Schema (~/.prism/plan_telemetry.db)
-----------------------------------
plans:
    plan_id           TEXT PRIMARY KEY
    request           TEXT     -- the user prompt that produced the plan
    primary_focus     TEXT
    rationale         TEXT
    created_at        REAL
    superseded_by     TEXT     -- plan_id of the replan output, or NULL

plan_steps:
    plan_id           TEXT
    step_index        INTEGER
    title             TEXT
    time_slot         TEXT
    duration_min      INTEGER
    category          TEXT
    notes             TEXT
    status            TEXT     -- pending | in_progress | done | abandoned | skipped
    outcome_record_id TEXT     -- link to outcomes.db (empty when unlinked)
    started_at        REAL
    completed_at      REAL
    PRIMARY KEY (plan_id, step_index)
"""
from __future__ import annotations

import logging
import sqlite3
import threading
import time
import uuid
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

STATUS_PENDING     = "pending"
STATUS_IN_PROGRESS = "in_progress"
STATUS_DONE        = "done"
STATUS_ABANDONED   = "abandoned"
STATUS_SKIPPED     = "skipped"

_VALID_STATUSES = {
    STATUS_PENDING, STATUS_IN_PROGRESS,
    STATUS_DONE,    STATUS_ABANDONED, STATUS_SKIPPED,
}


class PlanTelemetry:
    """SQLite-backed per-step telemetry for DailyPlan execution.

    Each plan generated by the KDE is persisted with stable plan_id + step
    indexes so subsequent chain outcomes (recorded by OutcomeTracker) can
    be linked back to the originating step. Re-plan reads completion stats
    from this store to inform the refinement prompt sent to KDE.
    """

    def __init__(self, db_path: str = "~/.prism/plan_telemetry.db") -> None:
        self._db   = Path(db_path).expanduser()
        self._db.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._init_db()

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def record_plan(self, plan: Any, request: str = "") -> str:
        """Persist a DailyPlan and its tasks. Returns the new plan_id.

        ``plan`` is duck-typed: anything with ``.primary_focus``, ``.rationale``,
        and ``.tasks`` (each task having ``.title``, ``.time_slot``,
        ``.duration_min``, ``.category``, ``.notes``) is accepted. Missing
        attributes default to empty strings / zero.
        """
        plan_id = str(uuid.uuid4())[:12]
        primary_focus = str(getattr(plan, "primary_focus", "") or "")[:200]
        rationale     = str(getattr(plan, "rationale", "") or "")[:1000]
        tasks         = list(getattr(plan, "tasks", []) or [])
        now = time.time()
        with self._lock, sqlite3.connect(self._db, timeout=30.0) as con:
            con.execute(
                "INSERT INTO plans VALUES (?,?,?,?,?,?)",
                (plan_id, request[:600], primary_focus, rationale, now, None),
            )
            for i, t in enumerate(tasks):
                con.execute(
                    "INSERT INTO plan_steps VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                    (
                        plan_id,
                        i,
                        str(getattr(t, "title", "") or "")[:200],
                        str(getattr(t, "time_slot", "") or "")[:32],
                        int(getattr(t, "duration_min", 0) or 0),
                        str(getattr(t, "category", "") or "")[:80],
                        str(getattr(t, "notes", "") or "")[:400],
                        STATUS_PENDING,
                        "",
                        None,
                        None,
                    ),
                )
        logger.debug("[plan_telemetry] recorded plan %s with %d steps", plan_id, len(tasks))
        return plan_id

    def mark_step(
        self,
        plan_id:           str,
        step_index:        int,
        status:            str,
        outcome_record_id: str = "",
        notes:             str = "",
    ) -> bool:
        """Update a single step's status and optionally its linked outcome_record_id.

        Returns ``True`` if a row was updated.
        Transitions to in_progress stamp ``started_at``; transitions to a
        terminal status (done/abandoned/skipped) stamp ``completed_at``.
        """
        if status not in _VALID_STATUSES:
            raise ValueError(f"invalid status: {status!r}")
        now = time.time()
        with self._lock, sqlite3.connect(self._db, timeout=30.0) as con:
            row = con.execute(
                "SELECT status, started_at, completed_at, notes "
                "FROM plan_steps WHERE plan_id=? AND step_index=?",
                (plan_id, step_index),
            ).fetchone()
            if row is None:
                return False
            old_status, started_at, completed_at, old_notes = row
            new_started_at   = started_at
            new_completed_at = completed_at
            if status == STATUS_IN_PROGRESS and started_at is None:
                new_started_at = now
            if status in (STATUS_DONE, STATUS_ABANDONED, STATUS_SKIPPED):
                new_completed_at = now
                if new_started_at is None:
                    new_started_at = now
            new_notes = notes.strip() or old_notes or ""
            con.execute(
                "UPDATE plan_steps SET status=?, outcome_record_id=?, "
                "started_at=?, completed_at=?, notes=? "
                "WHERE plan_id=? AND step_index=?",
                (
                    status, outcome_record_id or "",
                    new_started_at, new_completed_at, new_notes[:400],
                    plan_id, step_index,
                ),
            )
        logger.debug(
            "[plan_telemetry] %s/%d: %s → %s", plan_id, step_index, old_status, status
        )
        return True

    def supersede(self, old_plan_id: str, new_plan_id: str) -> bool:
        """Mark old_plan_id as replaced by new_plan_id. Idempotent."""
        with self._lock, sqlite3.connect(self._db, timeout=30.0) as con:
            cur = con.execute(
                "UPDATE plans SET superseded_by=? WHERE plan_id=? AND superseded_by IS NULL",
                (new_plan_id, old_plan_id),
            )
            return cur.rowcount > 0

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_plan(self, plan_id: str) -> Optional[dict]:
        """Return the plan + steps as a dict, or ``None`` if not found."""
        with sqlite3.connect(self._db, timeout=30.0) as con:
            prow = con.execute(
                "SELECT plan_id, request, primary_focus, rationale, created_at, superseded_by "
                "FROM plans WHERE plan_id=?",
                (plan_id,),
            ).fetchone()
            if prow is None:
                return None
            srows = con.execute(
                "SELECT step_index, title, time_slot, duration_min, category, notes, "
                "status, outcome_record_id, started_at, completed_at "
                "FROM plan_steps WHERE plan_id=? ORDER BY step_index",
                (plan_id,),
            ).fetchall()
        return {
            "plan_id":       prow[0],
            "request":       prow[1],
            "primary_focus": prow[2],
            "rationale":     prow[3],
            "created_at":    prow[4],
            "superseded_by": prow[5],
            "steps": [
                {
                    "step_index":        s[0],
                    "title":             s[1],
                    "time_slot":         s[2],
                    "duration_min":      s[3],
                    "category":          s[4],
                    "notes":             s[5],
                    "status":            s[6],
                    "outcome_record_id": s[7],
                    "started_at":        s[8],
                    "completed_at":      s[9],
                }
                for s in srows
            ],
        }

    def latest_plan(self) -> Optional[dict]:
        """Return the most recently created plan that has not been superseded."""
        with sqlite3.connect(self._db, timeout=30.0) as con:
            row = con.execute(
                "SELECT plan_id FROM plans WHERE superseded_by IS NULL "
                "ORDER BY created_at DESC LIMIT 1"
            ).fetchone()
        return self.get_plan(row[0]) if row else None

    def completion_stats(self, plan_id: str) -> dict:
        """Return a counts dict for the plan's step statuses."""
        with sqlite3.connect(self._db, timeout=30.0) as con:
            rows = con.execute(
                "SELECT status, COUNT(*) FROM plan_steps WHERE plan_id=? GROUP BY status",
                (plan_id,),
            ).fetchall()
        counts = {s: 0 for s in _VALID_STATUSES}
        for status, n in rows:
            counts[status] = n
        total = sum(counts.values())
        done  = counts[STATUS_DONE]
        counts["total"]           = total
        counts["completion_rate"] = round(done / total, 2) if total else 0.0
        return counts

    def telemetry_summary(self, plan_id: str) -> str:
        """One-line human-readable summary for the replan prompt."""
        p = self.get_plan(plan_id)
        if p is None:
            return ""
        done = [s for s in p["steps"] if s["status"] == STATUS_DONE]
        stalled = [
            s for s in p["steps"]
            if s["status"] in (STATUS_ABANDONED, STATUS_IN_PROGRESS)
        ]
        skipped = [s for s in p["steps"] if s["status"] == STATUS_SKIPPED]
        parts: list[str] = []
        if done:
            parts.append("Completed: " + "; ".join(s["title"] for s in done[:6]))
        if stalled:
            parts.append("Stalled: " + "; ".join(s["title"] for s in stalled[:6]))
        if skipped:
            parts.append("Skipped: " + "; ".join(s["title"] for s in skipped[:6]))
        return " | ".join(parts)

    # ------------------------------------------------------------------
    # Schema
    # ------------------------------------------------------------------

    def _init_db(self) -> None:
        with sqlite3.connect(self._db, timeout=30.0) as con:
            con.execute("""
                CREATE TABLE IF NOT EXISTS plans (
                    plan_id       TEXT PRIMARY KEY,
                    request       TEXT NOT NULL DEFAULT '',
                    primary_focus TEXT NOT NULL DEFAULT '',
                    rationale     TEXT NOT NULL DEFAULT '',
                    created_at    REAL NOT NULL,
                    superseded_by TEXT
                )
            """)
            con.execute("""
                CREATE TABLE IF NOT EXISTS plan_steps (
                    plan_id            TEXT NOT NULL,
                    step_index         INTEGER NOT NULL,
                    title              TEXT NOT NULL DEFAULT '',
                    time_slot          TEXT NOT NULL DEFAULT '',
                    duration_min       INTEGER NOT NULL DEFAULT 0,
                    category           TEXT NOT NULL DEFAULT '',
                    notes              TEXT NOT NULL DEFAULT '',
                    status             TEXT NOT NULL DEFAULT 'pending',
                    outcome_record_id  TEXT NOT NULL DEFAULT '',
                    started_at         REAL,
                    completed_at       REAL,
                    PRIMARY KEY (plan_id, step_index),
                    FOREIGN KEY (plan_id) REFERENCES plans(plan_id) ON DELETE CASCADE
                )
            """)
            con.execute(
                "CREATE INDEX IF NOT EXISTS ix_steps_status ON plan_steps(status)"
            )


_singleton: Optional[PlanTelemetry] = None
_singleton_lock = threading.Lock()


def get_plan_telemetry(db_path: str = "~/.prism/plan_telemetry.db") -> PlanTelemetry:
    """Process-wide singleton accessor, mirroring prism_settings_store.get_settings_store()."""
    global _singleton
    if _singleton is None:
        with _singleton_lock:
            if _singleton is None:
                _singleton = PlanTelemetry(db_path)
    return _singleton
